#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: docker.io/miyukis/gitops-go-app # 変更箇所 DOCKERHUB_REPO_NAME
  tag: 1

imageConfig:
  pullPolicy: IfNotPresent

#Service
service_type: LoadBalancer